### ISSUE TITLE
01-java-class-design wrong class

### ISSUE THREAD

**Issue by RafToTheK** [eh3rrera/ocpj8-notes#5]
In the "Inheritance" subsection there is the paragraph:

> So now Dog has two methods, eat() that is inherited from **Dog** and bark() that is specific to the Dog class. Animal still has one method, inheritance only works from the superclasses to the subclasses.

The bold Dog should be Animal

**Comment by eh3rrera** [comment]
Thanks @RafToTheK is fixed now.

These are only notes for the exam. You may want to check out a full book I wrote the OCPJ 8 certification. You can read it for free at http://ocpj8.javastudyguide.com/.

**Comment by RafToTheK** [comment]
Hi. Thanks for fixing. I actually started reading it, but I didn't finish, since I had to do a lot of other stuff. But maybe during the holidays. Thanks for the great effort.
